### ISSUE TITLE
Tags order from github api

### ISSUE THREAD

**Issue by MontakOleg** [marinofelipe/swift-package-info#15]
Hello!
Thank you for great tool!

`git/refs/tags` ordered alphabetically? instead of commit date, this leads to fails in some cases, for example for Realm:

`swift-package-info --for https://github.com/realm/realm-cocoa --product Realm`

Version `1.1.0-3` will be fetched (instead of `v10.7.0`)

https://api.github.com/repos/realm/realm-cocoa/git/refs/tags:
```
  ...
  {
    "ref": "refs/tags/v10.7.0",
    "node_id": "MDM6UmVmNDA0NDg5MTpyZWZzL3RhZ3MvdjEwLjcuMA==",
    "url": "https://api.github.com/repos/realm/realm-cocoa/git/refs/tags/v10.7.0",
    "object": {
      "sha": "1454f0c55ee856a3ca49c7a25c7bb0251810b2cf",
      "type": "tag",
      "url": "https://api.github.com/repos/realm/realm-cocoa/git/tags/1454f0c55ee856a3ca49c7a25c7bb0251810b2cf"
    }
  },
  {
    "ref": "refs/tags/vv5.0.0-beta.1",
    "node_id": "MDM6UmVmNDA0NDg5MTpyZWZzL3RhZ3MvdnY1LjAuMC1iZXRhLjE=",
    "url": "https://api.github.com/repos/realm/realm-cocoa/git/refs/tags/vv5.0.0-beta.1",
    "object": {
      "sha": "2b9516ed18e4f3a36fcfa7d5c14d33b491d62d91",
      "type": "tag",
      "url": "https://api.github.com/repos/realm/realm-cocoa/git/tags/2b9516ed18e4f3a36fcfa7d5c14d33b491d62d91"
    }
  },
  {
    "ref": "refs/tags/1.1.0-3",
    "node_id": "MDM6UmVmNDA0NDg5MTpyZWZzL3RhZ3MvMS4xLjAtMw==",
    "url": "https://api.github.com/repos/realm/realm-cocoa/git/refs/tags/1.1.0-3",
    "object": {
      "sha": "da3314d0b0afc45fd4b072275adda0299a3d3d20",
      "type": "tag",
      "url": "https://api.github.com/repos/realm/realm-cocoa/git/tags/da3314d0b0afc45fd4b072275adda0299a3d3d20"
    }
  }
```

May be we can ask github to sort tags, for example like this https://stackoverflow.com/a/47501956, but I'm not sure if we will get all tags in this case.

**Comment by marinofelipe** [comment]
Hey again @MontakOleg 👋 !
I'm glad you like the tool 😄 !

This is a good catch, I wrongly thought it was ordered by date 👍 .
I'll look into that after fixing #16. 

In any case, FYI the version can be manually passed in:
```
swift-package-info --for https://github.com/realm/realm-cocoa --product Realm [--v/--package-version] v10.7.0
```
So that's good at least that it's not a blocking issue.

Regarding the post you linked, it's a good finding, the bad is that the linked API is GitHubAPI v4 which is GraphQL based. 
Since the usages of GitHubAPI are fairly simple in this project, I'd like to avoid as much as possible changing from REST to GraphQL, although it seems that such feature is not available on v3 😢.

I'll further check this and get back to you. Let me know in case you are able to find any interesting alternative for this.

**Comment by marinofelipe** [comment]
Hi @MontakOleg , it's been a while, but I've just migrated to use the SwiftPM lib, so it should be now easier to resolve the latest tag :)

**Comment by marinofelipe** [comment]
If you wanna give it a try, https://github.com/marinofelipe/swift-package-info/pull/46 is out and I'll soon patch 1.4.1 with the fix
